### ISSUE TITLE
To-Do List App

### ISSUE THREAD

**Issue by samudralaAbhiramrao** [samudralaAbhiramrao/python-projects-Abhiram#4]
- [ ] code the APP
- [ ] update with a README file

> Readme need to contain:

- [ ] Python libraries installed 
- [ ] Installation code
- [ ] code functionality description
- [ ] Upload the output as images

**Comment by samudralaAbhiramrao** [comment]
added this as a milestone
